package com.bankguard.common.constant;

public enum ErrorCode {
    VALIDATION_ERROR,
    IDEMPOTENCY_KEY_REQUIRED,
    INVALID_CHANNEL,
    INVALID_IP_ADDRESS,
    INVALID_DATE_RANGE,
    INVALID_PAGE_SIZE,
    UNAUTHORIZED,
    FORBIDDEN,
    TRANSACTION_NOT_FOUND,
    SOURCE_ACCOUNT_NOT_FOUND,
    CUSTOMER_NOT_FOUND,
    TRUSTED_DEVICE_NOT_FOUND,
    BLACKLISTED_ACCOUNT_NOT_FOUND,
    RISK_RULE_NOT_FOUND,
    SOURCE_ACCOUNT_INACTIVE,
    DUPLICATE_RESOURCE,
    INTERNAL_SERVER_ERROR,
    EVENT_PUBLISH_FAILED,
    DEPENDENCY_UNAVAILABLE
}
